# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('std_id', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
    ]
